### ISSUE TITLE
Health check and ready check are unnecessary

### ISSUE THREAD

**Issue by intel352** [go-coldbrew/cookiecutter-coldbrew#9]
gRPC in Go already provides a built-in health check which can also be used for your readiness check.
https://pkg.go.dev/google.golang.org/grpc/health

I'm referring to your definition of custom rpc endpoints for health/readiness.
https://github.com/go-coldbrew/cookiecutter-coldbrew/blob/c54fcc2811a20bdfb7a58c46544d13e31a007331/%7B%7Bcookiecutter.app_name%7D%7D/proto/%7B%7Bcookiecutter.app_name%7Clower%7D%7D.proto#L34

**Comment by ankurs** [comment]
Hey @intel352 Thanks for the bug, we have since moved to these custom definition

let me know if you feel this still needs to be addressed
